### ISSUE TITLE
Kontaktverfolgung in Rheinland-Pfalz, Änderungen vom 22.12.21

### ISSUE THREAD

**Issue by LongHairedHacker** [wasserbombe/lucafail-timeline#13]
Moin,

auf der Karte is RLP noch rot, d.h. `Kontaktdatenerfassung und/oder Luca vorgeschrieben`.

Ich habe neulich zufällig mal in die aktuelle Fassung der [Neunundzwanzigste Corona-Bekämpfungsverordnung Rheinland-Pfalz ](https://corona.rlp.de/fileadmin/corona/Verordnungen/29._CoBeVo/211222_29_CoBeLVO_1AEndVO_konsolidierte_Fassung_001.pdf) geschaut und dort folgenden neuen Zusatz entdeckt:

In § 3 Absatz 4 steht ganz am Ende:
```
Die Kontakterfassung nach Satz 1 ist nicht
erforderlich, wenn die Person, deren Daten zu erfassen sind, die in der Corona-Warn-App
des Robert Koch-Instituts enthaltene QR-Code-Registrierung nutzt und die oder der
ansonsten zur Datenerhebung Verpflichtete dies in geeigneter Weise überprüft.
```

Der Satz 1 auf den sich da bezogen wird lautet:
```
Der Betreiber einer Einrichtung oder Veranlasser einer Ansammlung oder sonstigen
Zusammenkunft in geschlossenen Räumen hat die Kontaktnachverfolgbarkeit
sicherzustellen, sofern dies in dieser Verordnung bestimmt wird; werden gegenüber der oder
dem zur Datenerhebung Verpflichteten Kontaktdaten angegeben, müssen diese
wahrheitsgemäß sein und eine Kontaktnachverfolgung ermöglichen (Kontakterfassung).
```

Für mich liest sich das so, dass der Betreiber nicht mehr verpflichtet ist Kontaktdaten zu erfassen,
wenn er im Gegenzug prüft, dass sich die Person mit der CWA an seiner Location eingecheckt hat.

Das war wohl eine [Änderung](https://corona.rlp.de/fileadmin/corona/Verordnungen/29._CoBeVo/211222_29_CoBeLVO_1_AEndVO_AEnderungsVO_001.pdf) am 22.12 zu der Verordnung von 3.12.

Damit wäre ja die anonymen Kontaktnachverfolgung mit der CWA eine gleichwertige Alternative und man könnte die Karte auf grün ändern.

Oder habe ich da irgendwas übersehen?

**Comment by wasserbombe** [comment]
Hey @LongHairedHacker, danke für Deinen Beitrag! Nein, Du hast nichts übersehen - aber ich. Ich hatte nur mit der ursprünglichen Fassung der 29. CoronaVO gearbeitet und nicht bemerkt, dass es am 22.12. nochmal ein Update gab. Ist nun gefixt + deployt: https://github.com/wasserbombe/lucafail-timeline/commit/33ba191a0f7daf5097d08ab17f709c05deb2899b

Viele Grüße und Danke
Sebastian
