### ISSUE TITLE
butenunbinnen.de: Bremen lässt Vertrag für Luca-App auslaufen

### ISSUE THREAD

**Issue by LongHairedHacker** [wasserbombe/lucafail-timeline#14]
Hallo,

ich bin gerade auf mastodon ([siehe toot](https://chaos.social/web/statuses/107620880915336347)) über folgendes Interview gestolpert:
https://www.butenunbinnen.de/nachrichten/aus-luca-app-bremen-100.html

Dachte das passt ganz gut in die Timeline als followup zu https://www.butenunbinnen.de/nachrichten/luca-app-bremen-vertrag-102.html

Grüße,
Sebastian

**Comment by wasserbombe** [comment]
Hey @LongHairedHacker, 

vielen lieben Dank für den guten Hinweis! Ich habe den Artikel soeben in der Timeline ergänzt, den alten referenziert und die Vertragskündigung auch bei [luca.fail](https://luca.fail/) / [wasserbombe/lucafail](https://github.com/wasserbombe/lucafail) erfasst. 

Viele Grüße
Sebastian
