### ISSUE TITLE
noch mehr fragdenstaat.de

### ISSUE THREAD

**Issue by wolf128058** [wasserbombe/lucafail-timeline#3]
Hallo @wasserbombe,

vielen Dank für diese herrliche Übersicht.
Wirklich hilfreich, wenn man sich einen Überblick verschaffen möchte.

Einen ganz anderen Überblick hätte ich hier noch zu den Anfragen via fragdenstaat,
von denen es sich bei der einen oder anderen vielleicht lohnt, hier eingewoben zu werden.

Ich hätte dir noch ein paar Kandidaten für einen Eintrag:
* Das Gesundheitsamt Bremen mag sich zu Lizenzkosten/Datenschutz/Vertrag nicht äußern. https://fragdenstaat.de/a/218870
* Das Gesundheitsamt Solingen verweigert die Auskunft zu Beschaffungsprozess und datenschutzrechtlicher Bewertung https://fragdenstaat.de/a/224806
* Die Stadt Suhl kann den Vertrag nicht uploaden, da mit dem Vertragspartner eine entsprechende Vertraulichkeitsklausel geschlossen wurde. https://fragdenstaat.de/a/217273
* Der Landkreis Ravensburg antwortet seit 03.04.2021 nicht. Auch zweimal vom LfDI darum gebeten zu werden juckt die nicht. https://fragdenstaat.de/a/217308
* Von der Stadt Jena haben wir den Vertrag zu sehen bekommen. https://fragdenstaat.de/a/217359
* Das Ministerium für Soziales, Gesundheit, Integration und Verbraucherschutz Brandenburg lehnt wegen Betriebs- und Geschäftsgeheimnissen ab, den Vertrag offenzulegen. https://fragdenstaat.de/a/216805
* Die hessische Staatskanzlei sieht für die Herausgabe des Vertragswerks ein „Verfahren bei Beteiligung Dritter“ und veranschlagt Kosten bis zu 600 EUR https://fragdenstaat.de/a/216803
* In Baden-Württemberg will das Ministerium für Soziales und Integration den gewünschten Vertrag, vor allem aufgrund der derzeit noch laufenden vergaberechtlichen Fristen, nicht zur Verfügung stellen. https://fragdenstaat.de/a/216802
* Das Ministerium für Soziales, Gesundheit, Jugend, Familie und Senioren Schleswig-Holstein übermittelt uns den Vertrag https://fragdenstaat.de/a/216804
* Und die Bundesdruckerei (GmbH) verweigert alle Auskünfte mit dem Hinweis, sie habe sich als juristische Person des Privatrechts nicht an IFG zu halten. https://fragdenstaat.de/a/219865

Herzliche Grüße
Wolf

**Comment by wasserbombe** [comment]
Hallo @wolf128058, 

freut mich, wenn die Timeline so gut ankommt!
Und vielen lieben Dank für den Input! Ich habe alle genannten IFG-Anfragen mit in der Timeline aufgenommen. Die Anfrage zur Bundesdruckerei war schon enthalten, aber in einem anderen Zusammenhang - diese bekommt nun einen einzelnen Punkt. 

Viele Grüße und danke nochmal!
Sebastian
