### ISSUE TITLE
Süddeutsche : Die teure App, die wenig bringt

### ISSUE THREAD

**Issue by Siedlerchr** [wasserbombe/lucafail-timeline#5]
>In Nordrhein-Westfalen könnte die Luca-Nutzung für Gastronomen demnächst sogar rechtlich problematisch werden. Seit Freitag ist die Nachverfolgung von Kontakten dort nicht mehr Teil der Corona-Schutzverordnung, für die Erhebung der Daten ohne Einwilligung fehlt also die Rechtsgrundlage. Luca habe die Betreiber in einer Mail darüber informiert, schreibt Luca-Sprecher Markus Bublitz auf Twitter. Von einem rechtlichen Risiko ist in den Mails allerdings keine Rede.

https://www.sueddeutsche.de/wirtschaft/luca-app-kritik-1.5388136

**Comment by wasserbombe** [comment]
@Siedlerchr Danke, habe ich hinzugefügt! :)
