### ISSUE TITLE
Saarland: Luca-App im Saarland bislang ein Flop 

### ISSUE THREAD

**Issue by Siedlerchr** [wasserbombe/lucafail-timeline#6]
>Aus einer SR-Anfrage an die saarländischen Gesundheitsämter geht hervor: Bei über 13.000 bestätigten Corona-Infektionen seit April gab es keinen einzigen Fall, bei dem die App geholfen hätte, Kontaktpersonen zu ermitteln und zu informieren. Mehrere Gesundheitsämter haben demnach bisher noch keine einzige Abfrage über die Luca-App gestartet.

https://www.sr.de/sr/home/nachrichten/politik_wirtschaft/luca-app_im_saarland_bislang_ein_flop_100.html

**Comment by wasserbombe** [comment]
Danke @Siedlerchr! Habe ich hinzugefügt!
