### ISSUE TITLE
 Nutzung der Luca-App fällt in Schleswig-Holstein weg 

### ISSUE THREAD

**Issue by Siedlerchr** [wasserbombe/lucafail-timeline#7]
Ist in NRW ja auch schon so:

 Mit einer neuen Corona-Landes­verordnung entfällt in Schleswig-Holstein die Pflicht zur Kontakt­daten­erhebung bei Veranstaltungen oder in der Gastronomie – und damit auch die Nutzung der Luca-App.

https://www.rnd.de/gesundheit/luca-app-in-schleswig-holstein-wird-sie-nicht-mehr-gebraucht-TBFB3WZVBZD7FJLZBLTLY2QBCU.html

**Comment by wasserbombe** [comment]
Danke @Siedlerchr, habe ich mit aufgenommen!
