### ISSUE TITLE
Keine Anonyme Kontaktverfolgung in Bremen

### ISSUE THREAD

**Issue by Janfred** [wasserbombe/lucafail-timeline#9]
Bremen hat die CWA nach nur 4 Tagen wieder aus der Verordnung entfernt und erlaubt damit nicht die anonyme Kontaktdatenerfassung (und hat sie formal-juristisch vmtl auch nie erlaubt, weil der Gesetzestext schlampig geschrieben wurde [meine Meinung])

Aktuelle Verordnung: https://www.transparenz.bremen.de/metainformationen/neunundzwanzigste-verordnung-zum-schutz-vor-neuinfektionen-mit-dem-coronavirus-sars-cov-2-neunundzwanzigste-coronaverordnung-vom-28-september-2021-174654?asl=bremen203_tpgesetz.c.55340.de&template=20_gp_ifg_meta_detail_d

Alte Version mit CWA: https://www.transparenz.bremen.de/metainformationen/neunundzwanzigste-verordnung-zum-schutz-vor-neuinfektionen-mit-dem-coronavirus-sars-cov-2-neunundzwanzigste-coronaverordnung-vom-28-september-2021-174546?asl=bremen203_tpgesetz.c.55340.de&template=20_gp_ifg_meta_detail_d

Das Gesetzblatt, das das geändert hat: https://www.gesetzblatt.bremen.de/fastmedia/218/2021_12_09_GBl_Nr_0136_signed.pdf

**Comment by wasserbombe** [comment]
Hey @Janfred, 
herzlichen Dank für Deinen Hinweis! Ich habe das in der Karte korrigiert und Links zur Verordnung hinzugefügt.

**Comment by viisauksena** [comment]
#bremen doch Grün , fyi 
"ich darf Sie auch auf die Begründung der Verordnung hinweisen: https://www.amtliche-bekanntmachungen.bremen.de/amtliche-bekanntmachungen/begruendung-der-fuenften-verordnung-zur-aenderung-der-neunundzwanzigsten-verordnung-zum-schutz-vor-neuinfektionen-mit-dem-coronavirus-sars-cov-2-16271?asl=bremen02.c.730.de

Ja, wer nur mit der CWA eincheckt erfüllt die Anforderungen der Verordnung.
"

**Comment by Janfred** [comment]
Jein. Der Gesetzestext sagt, dass die Kontaktdaten (Name AND (Telefonnummer OR Mailadresse) ) hinterlegt werden müssen. und das kann auch digital erfolgen. So wie ich den Gesetzestext lese darf die CWA nicht verwendet werden, weil sie genau das ja eben nicht kann.
Der Gesetzgeber mag hier vorgesehen haben, dass man auch mit der CWA einchecken kann. Das ist aber nicht korrekt und rechtssicher umgesetzt. (Zugegeben, ziemlich traurig, aber leider nichts neues)

@viisauksena hast du zu dem ergänzenden Text eine Quelle? Das sieht wie ein Mailtext zu einer Anfrage oder einem Tweet aus.

**Comment by viisauksena** [comment]
@Janfred  wir haben aufgrund deiner Anmerkung vom CCCFr/Chaosradio mehrfach bei der Pressestelle Bremen angefragt, das oben war die Antwort auf die sehr konkrete Frage ob ersatzweise die Corona Warn App erlaubt werden kann. Hier die Fragen:

> bezüglich der Beschlüsse des Senats, im Konkreten
> "Erfassung von Kontaktdaten ist ab sofort auch mit der Corona-Warn-App möglich"
> siehe dazu auch ihre Pressemitteilung
> https://www.senatspressestelle.bremen.de/pressemitteilungen/senat-beschliesst-anpassung-der-bremer-corona-verordnung-373930?asl=bremen02.c.730.de
> 
> Die CoronaVo wurde nun anscheinend nach kurzer Zeit erneut geändert,
siehe : https://github.com/wasserbombe/lucafail-timeline/issues/9#issue-1081412606
es liest sich nichts mehr von dem Einsatz der Corona Warn App,
kann diese weiterhin für einen Check-In in Bremen genutzt werden?

infolge nochmal Konkretisiert am Donnerstag
> wir finden das weiterhin Mißverständlich ausgedrückt. Es lässt sich in beide Richtungen lesen. Insbesondere da sie ein hartes Kontroll und Strafregime ankündigen möchten wir klärend noch einmal Fragen:
> 
> Erfüllt jemand der mit der Corona Warn App eincheckt die Anforderungen der Bremer CoronaVO?
D.h. diese Person muss nicht Papierzettel ausfüllen oder die Luca/Gast Bremen App zusätzlich nutzen.

zuletzt Antwortet der Pressesprecher der Hansestadt Bremen
> ich darf Sie auch auf die Begründung der Verordnung hinweisen: https://www.amtliche-bekanntmachungen.bremen.de/amtliche-bekanntmachungen/begruendung-der-fuenften-verordnung-zur-aenderung-der-neunundzwanzigsten-verordnung-zum-schutz-vor-neuinfektionen-mit-dem-coronavirus-sars-cov-2-16271?asl=bremen02.c.730.de
> 
> Ja, wer nur mit der CWA eincheckt erfüllt die Anforderungen der Verordnung.

**Wir gehen also davon aus das ein Checkin im der Corona Warn App möglich ist.**
